actuator 헬스체크 추가, deploy.yml 백업, 헬스체크 추가

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,6 +28,7 @@ jobs:
           echo "Current branch: $BRANCH_NAME"
           echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
           echo "TARGET_DIR=$BASE_PATH/$BRANCH_NAME/app"  >> $GITHUB_ENV
+          echo "DEPLOY_DIR=$BASE_PATH/$BRANCH_NAME/deploy"  >> $GITHUB_ENV
           echo "SERVICE_NAME=$BRANCH_NAME" >> $GITHUB_ENV
 
 
@@ -48,22 +49,69 @@ jobs:
         run: |
           cd $TARGET_DIR
           mvn clean package -DskipTests
-          cp target/*.jar $BASE_PATH/$BRANCH_NAME/deploy/app.jar
+          
+          cd $DEPLOY_DIR
+          if [ -f "app.jar" ]; then
+            mv app.jar "app.jar.$(date +'%Y%m%d%H%M%S')"
+          fi
+
+          
+          cp $TARGET_DIR/target/*.jar $DEPLOY_DIR/app.jar
           echo "Restarting service $SERVICE_NAME"
           sudo systemctl restart $SERVICE_NAME          
 
+      - name: Health check dev
+        if: github.ref == 'refs/heads/dev'
+        run: |
+          echo "Running health check on port 9093..."
+          for i in {1..10}; do
+            if curl -fs http://localhost:9093/actuator/health; then
+              echo "Health check passed"
+              exit 0
+            fi
+            echo "Waiting for service..."
+            sleep 5
+          done
+
+          echo "Health check failed"
+          exit 1
+
+      - name: Set image tag
+        id: vars
+        run: |
+          DATE=$(date +%Y%m%d)
+          COMMIT=$(git rev-parse --short HEAD)
+          echo "TAG=${DATE}-${COMMIT}" >> $GITHUB_ENV
+          echo "TAG_NAME=${DATE}-${COMMIT}"
+                    
       - name: Deploy main
         if: github.ref == 'refs/heads/main'
         env:
-         IMAGE_NAME: toychat-main:latest
+         IMAGE_BASE: toychat-main
          COMPOSE: ${{ env.BASE_PATH }}/${{ env.BRANCH_NAME }}/docker/docker-compose.yml 
         run: |
           cd $TARGET_DIR
+          
           docker compose -f $COMPOSE down
-          docker build -t $IMAGE_NAME .
+          
+          docker build -t $IMAGE_BASE:latest .
+          docker build -t $IMAGE_BASE:$TAG .
+          
           docker compose -f $COMPOSE up -d --build
           echo "Restarting service $SERVICE_NAME ..."
 
+      - name: Health check main
+        if: github.ref == 'refs/heads/main'
+        run: |
+          echo "Running health check for main..."
+          sleep 10
+          if ! curl -fs http://localhost:9090/actuator/health; then
+            echo "Main health check failed. Rolling back..."
+            exit 1
+          else
+            echo "✅ Main service healthy."
+          fi
+          
       - name: PR build check
         if: github.event_name == 'pull_request' && github.base_ref == 'main'
         run: |
